---
# file: roles/iontorrent_computes/tasks/main.yml

- name:
  include: '../../../globals.yml'
#-----------------------------------------------------------------------------
# Install system packages specifically for a compute node
#-----------------------------------------------------------------------------
- name: Update apt cache
  apt: update_cache=yes
  register: aptcache
  ignore_errors: yes

- name: Fail when updating apt cache has failed in network environment
  fail:
    msg: "apt-get update has failed"
  when:
    - aptcache.failed
    - has_network_access
  
- name: Install system packages for compute resource - apt
  apt: name={{ item }} state=present force=yes
  with_items: "{{ ioncompute_syspkg_list }}"
  when:
   - item != ''
   - has_network_access

#-----------------------------------------------------------------------------
# Install Ion Torrent Packages for a compute node
#-----------------------------------------------------------------------------
- name: Install Ion packages for compute resource - apt
  apt: name={{ item }} state=present force=yes
  with_items: "{{ ioncompute_ionpkg_list }}"
  when:
    - item != ''
    - has_network_access

# Set host location of Ion Torrent Server Daemons
#function config_cluster_settings()
- name: Update cluster configuration file - local_cluster_settings.py
  lineinfile: dest={{ tsconfig_dir }}/local_cluster_settings.py
                state=present
                create=yes
                owner=ionadmin group=ionadmin mode=0644
                regexp="^{{ item }}.*"
                line="{{ item }} = '{{ groups.headnode[0] }}'"
  with_items:
    - PLUGINSERVER_HOST
    - JOBSERVER_HOST
    - CRAWLER_HOST

#-----------------------------------------------------------------------------
# Additional configuration steps
#-----------------------------------------------------------------------------
- include: software_update.yml
