---
# file: roles/iontorrent_computes/tasks/software_update.yml

# Configuration outside of deb package install that needs to happen on compute nodes.

#-----------------------------------------------------------------------------
# Copy scripts for cluster_info.py run from headnode
#-----------------------------------------------------------------------------
- name: Copy grp_mount_test script
  copy:
    src: /usr/sbin/grp_mount_test
    dest: /usr/sbin/grp_mount_test
    mode: 0775

- name: Copy grp_configuration_test script
  copy:
    src: /usr/sbin/grp_configuration_test
    dest: /usr/sbin/grp_configuration_test
    mode: 0775
