---
# file: site.yml
# The ordering of these operations matters
- include: common.yml               # Common settings
- include: db.yml                   # Postgresql server
- include: nfs_client.yml           # Configure NFS mountpoints
- include: webserver.yml            # Apache2 server
- include: fileserver.yml           # Handles direct-connect sequencers
- include: gridengine_master.yml    # Gridengine master host
- include: gridengine_clients.yml   # Gridengine exec host
- include: iontorrent_master.yml    # Headnode
- include: iontorrent_auxiliary.yml # Headnode only
- include: instrument_update.yml    # Headnode only
- include: iontorrent_computes.yml  # Compute nodes (or headnode if stand-alone)
- include: igv.yml                  # ion-plugins no long pulls in ion-jk and ion-igv
