---

- name: flush iptables
  shell: bash -lc '/sbin/iptables -F && iptables -P INPUT ACCEPT'
  
- name: load iptables
  shell: bash -lc '/sbin/iptables-restore < /etc/iptables.rules'
  
- name: load custom iptables
  shell: bash -lc '/sbin/iptables-restore --noflush < /etc/iptables.custom'
  
- name: restart dhcp
  service: name=dhcp3-server state=restarted
  ignore_errors: yes
  
- name: restart isc-dhcp
  service: name=isc-dhcp-server state=restarted
  ignore_errors: yes
  
- name: restart vsftpd
  service: name=vsftpd state=restarted
  
- name: restart ntp
  service: name=ntp state=restarted
  
- name: restart exportfs
  shell: bash -lc 'exportfs -ra'
  
- name: resolvconf update
  shell: bash -lc 'resolvconf -u'
