---
# file: roles/iontorrent_master/handlers/main.yml
- name: restart ionJobServer
  service: name=ionJobServer state=restarted
- name: restart ionPlugin
  service: name=ionPlugin state=restarted
- name: restart ionCrawler
  service: name=ionCrawler state=restarted
- name: update grub
  command: /usr/sbin/update-grub
  when: not docker_image

- name: reload systemd daemon
  command: systemctl daemon-reload

- name: restart systemd-udevd
  command: service systemd-udevd --full-restart
